[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "Ticket_Checker"
description = "Checks FreshService tickets to see if open tickets are closed, and if so, will update the D.B. with that and update the json and conversation fields"
version = "1.0"
requires-python = ">=3.10"

[project.scripts]
tc = "app.main:runner"
